name: Bug Report
description: Submit a bug you found in the software
body:
  - type: markdown
    attributes:
      value: |
        **GitHub Issues are not a support channel**.
        Please use Discord or the Forums if you need help or have a question
  - type: textarea
    attributes:
      label: Describe the Bug
  - type: textarea
    attributes:
      label: Expected Behaviour
  - type: textarea
    attributes:
      label: Steps to Reproduce the Bug
  - type: input
    attributes:
      label: Version
      placeholder: Version \# (or output of `git describe --tags` if running from source)
  - type: checkboxes
    attributes:
      label: OS
      options:
        - label: MacOS
        - label: Windows
        - label: Linux
  - type: textarea
    attributes:
      label: Additional Context

