blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.morpheus636.com
    about: Discuss or ask questions in Discord
  - name: Twitter
    url: https://twitter.com/morpheus636
  - name: Website
    url: https://morpheus636.com
  - name: Email
    url: mailto:morpheus636@morpheus636.com
    about: Contact me directly
